version: "3.9"

services:
  adminer:
    image: adminer
    ports:
      - 54323:8080
    environment:
      - ADMINER_PLUGINS=enum-types
    networks:
      - social-network
    deploy:
      placement:
        constraints:
          - node.role == manager
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/tsuwari_postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/tsuwari_postgres_password
      POSTGRES_DB_FILE: /run/secrets/tsuwari_postgres_db
    secrets:
      - tsuwari_postgres_user
      - tsuwari_postgres_password
      - tsuwari_postgres_db
    networks:
      - social-network
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 30
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager
    