version: '3.9'

services:
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8085:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
  
  postgres:
    restart: unless-stopped
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: sn_auth
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d sn_auth" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres-data: