version: "3"

includes:
  front:
    taskfile: ./frontend/main/Taskfile.yaml
    dir: ./frontend/main
  mailer:
    taskfile: ./apps/mailer/Taskfile.yaml
    dir: ./apps/mailer
  auth:
    taskfile: ./apps/auth/Taskfile.yaml
    dir: ./apps/auth
  api:
    taskfile: ./apps/api/Taskfile.yaml
    dir: ./apps/api
  grpc:
    taskfile: ./libs/grpc/Taskfile.yaml
    dir: ./libs/grpc
  migrations-runner:
    taskfile: ./tools/migrations-runner/Taskfile.yaml
    dir: ./tools/migrations-runner

tasks:
  migrations-up-prod:
    cmds:
      - task: migrations-runner:run
  migrations-up-dev:
    cmds:
      - task: migrations-runner:dev
  run-grpc:
    cmds:
      - task: grpc:run
  build-libs:
    deps: [run-grpc]
  prepare:
    deps: [migrations-up-dev]
    run: once
    cmds:
      - task: build-libs
  mailer-dev:
    deps: []
    cmds:
      - task: mailer:dev
  auth-dev:
    deps: [prepare]
    cmds:
      - task: auth:dev
  api-dev:
    deps: [prepare]
    cmds:
      - task: api:dev
  front-dev:
    cmds:
      - task: front:dev
  dev:
    deps: [api-dev, auth-dev, mailer-dev, front-dev]
