version: "3"

tasks:
  migrateup_dev:
    cmds:
      - migrate -path internal/db/migration -database "postgresql://test:test@localhost:5432/sn_auth?sslmode=disable" -verbose up

  migratedown_dev:
    cmds:
      - migrate -path internal/db/migration -database "postgresql://test:test@localhost:5432/sn_auth?sslmode=disable" -verbose down

  migrateup:
    cmds:
      - migrate -path internal/db/migration -database "postgresql://test:test@localhost:5432/sn_auth?sslmode=disable" -verbose up

  sqlc:
    cmds:
      - sqlc generate --experimental

  dev:
    deps: [migrateup_dev]
    cmds:
      - reflex -s -r '\.go' -- go run ./cmd/main.go
