apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-secret
  labels:
    app: socialy-auth
data:
  APP_ENV: development
  JWT_SECRET: Iag1ZinWKfZbvlNKhqOMgbluojBNERTC
  ACCESS_TOKEN_DURATION: "15m"
  REFRESH_TOKEN_DURATION: "24h"
  REDIS_ADDRESS: "0.0.0.0:6379"
  MAIL_HOST: localhost
  MAIL_PORT: "1025"
  MAIL_USER: test
  MAIL_PASS: test
  KAFKA_URL: kafka-service:9092
  SCHEMA_REGISTRY_URL: http://schemaregistry:31421
  SCHEMAS_PATH: /schemas/
  API_GATEWAY_PORT: "3001"
  DATABASE_URL: postgres://test:test@postgresdb:30829/sn_auth?sslmode=disable
  APP_ENV: development
  SITE_URL: localhost:5173/
  PASETO_SECRET: Iag1ZinWKfZbvlNKhqOMgbluojBNERTC
  MIGRATIONS_PATH: /migration
