apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
    - name: https
      port: 5000
      targetPort: 5000
      nodePort: 30000
