// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	VerifyEmail(ctx context.Context, arg VerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
