version: "3"

tasks:
  migrateup_dev:
    cmds:
      - goose -v -dir "internal/db/migration" postgres "postgresql://test:test@localhost:5432/sn_auth?sslmode=disable" up

  migratedown_dev:
    cmds:
      - goose -v -dir "internal/db/migration" postgres "postgresql://test:test@localhost:5432/sn_auth?sslmode=disable" down

  migrateup:
    cmds:
      - goose -v -dir "internal/db/migration" postgres {{.DB_URL}} up

  new_migration:
    cmds:
      - goose -v -dir "internal/db/migration" create {{.NAME}} sql

  sqlc:
    cmds:
      - sqlc generate --experimental

  gqlgen:
    cmds:
      - go generate ./...

  dev:
    deps: [gqlgen]
    cmds:
      - reflex -s -r '\.go' -- go run ./cmd/main.go
